version: 2
updates:
  - directory: /
    package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
      time: '04:00'
    ignore:
      - dependency-name: 'puppeteer'
        update-types: ['version-update:semver-major']
