name: Generate README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        run: npm install
      - name: generate README file
        run: node index.js
      - name: push updated README.md
        uses: mikeal/publish-to-github-action@master
        env:
          BRANCH_NAME: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
