name: Generate README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: install dependencies
        run: npm install
      - name: generate README file
        run: node index.js
      - name: push updated README.md
        uses: mikeal/publish-to-github-action@master
        env:
          BRANCH_NAME: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
